version: "3.8"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - ./web/.env
    depends_on:
      - database
    ports:
      - 8000:8000

  database:
    image: postgres:16
    env_file:
      - ./database/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: